one_hot_reconst: False
defaults:
  - models: gcn
  - datasets: bbbp
  - explainers: subgraphx
random_seed: 0
device_id: 0
record_filename: none
explain:
  max_nodes: 8
  top_m: 1
  top_r: 1
  threshold_whole: 0.8
  threshold_subgraph: 0.8
run:
  reconstruction_deconstruction: true
  random_baselines: true  
  
